payloadsGRRequest = [
    {
        "version": 36,
        "language": "de",
        "start": {
            "name": "Wartenau",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:10901",
        },
        "dest": {
            "name": "Ritterstraße",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:60904",
        },
        "toStartBy": "FOOTPATH",
        "toDestBy": "FOOTPATH",
        "time": {"date": "heute", "time": "jetzt"},
        "timeIsDeparture": True,
        "schedulesBefore": 0,
        "schedulesAfter": 4,
        "intermediateStops": True,
        "tariffInfoSelector": [
            {"tariff": "HVV", "tariffRegions": True, "kinds": ["1"]},
            {"tariff": "SH", "tariffRegions": False, "kinds": ["1"]},
        ],
        "penalties": [
            {
                "name": "desiredType",
                "value": "longdistancebus,fasttrain&extrafasttrain:10000",
            }
        ],
        "returnContSearchData": True,
        "realtime": "REALTIME",
    },
    {
        "start": {
            "name": "Wartenau",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:10901",
        },
        "dest": {
            "name": "Ritterstraße",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:60904",
        },
    },
    {
        "start": {
            "name": "Wartenau",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:10901",
        },
        "dest": {
            "name": "Ritterstraße",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:60904",
        },
        "timeIsDeparture": False,
    },
    {
        "start": {
            "name": "Wartenau",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:10901",
        },
        "dest": {
            "name": "Ritterstraße",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:60904",
        },
        "penalties": [
            {
                "name": "desiredType",
                "value": "longdistancebus,fasttrain&extrafasttrain:10000",
            },
            {"name": "ToStartStationBy", "value": "1",},
            {"name": "TimeRange", "value": "100",},
            {"name": "ForVisitors", "value": "1",},
        ],
    },
    # Requests from hvv website
    {
        "version": 36,
        "language": "de",
        "start": {
            "name": "Von-Sauer-Straße",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:80101",
        },
        "dest": {
            "name": "Beethovenstraße",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:70036",
        },
        "toStartBy": "FOOTPATH",
        "toDestBy": "FOOTPATH",
        "time": {"date": "heute", "time": "jetzt"},
        "timeIsDeparture": True,
        "schedulesBefore": 0,
        "schedulesAfter": 4,
        "intermediateStops": True,
        "tariffInfoSelector": [
            {"tariff": "HVV", "tariffRegions": True, "kinds": ["1"]},
            {"tariff": "SH", "tariffRegions": False, "kinds": ["1"]},
        ],
        "penalties": [
            {
                "name": "desiredType",
                "value": "longdistancebus,fasttrain&extrafasttrain:10000",
            }
        ],
        "returnContSearchData": True,
        "realtime": "REALTIME",
    },
    {
        "version": 36,
        "language": "en",
        "start": {
            "name": "Hamburg-Harburg",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:8000147",
        },
        "dest": {
            "name": "Stade",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:8000089",
        },
        "toStartBy": "FOOTPATH",
        "toDestBy": "FOOTPATH",
        "time": {"date": "heute", "time": "jetzt"},
        "timeIsDeparture": True,
        "schedulesBefore": 0,
        "schedulesAfter": 4,
        "intermediateStops": True,
        "tariffInfoSelector": [
            {"tariff": "HVV", "tariffRegions": True, "kinds": ["1"]},
            {"tariff": "SH", "tariffRegions": False, "kinds": ["1"]},
        ],
        "penalties": [
            {
                "name": "desiredType",
                "value": "longdistancebus,fasttrain&extrafasttrain:10000",
            }
        ],
        "returnContSearchData": True,
        "realtime": "REALTIME",
    },
    {
        "version": 36,
        "language": "de",
        "start": {
            "name": "Modering",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:86004",
        },
        "dest": {
            "name": "Stade",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:8000089",
        },
        "toStartBy": "FOOTPATH",
        "toDestBy": "FOOTPATH",
        "time": {"date": "13.02.2020", "time": "14:24"},
        "timeIsDeparture": True,
        "schedulesBefore": 0,
        "schedulesAfter": 4,
        "intermediateStops": True,
        "tariffInfoSelector": [
            {"tariff": "HVV", "tariffRegions": True, "kinds": ["1"]},
            {"tariff": "SH", "tariffRegions": False, "kinds": ["1"]},
        ],
        "penalties": [
            {
                "name": "desiredType",
                "value": "longdistancebus,fasttrain&extrafasttrain:10000",
            }
        ],
        "returnContSearchData": True,
        "realtime": "REALTIME",
    },
    {
        "version": 36,
        "language": "de",
        "start": {
            "name": "Modering",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:86004",
        },
        "dest": {
            "name": "Stade",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:8000089",
        },
        "toStartBy": "FOOTPATH",
        "toDestBy": "FOOTPATH",
        "time": {"date": "13.02.2020", "time": "14:24"},
        "timeIsDeparture": True,
        "schedulesBefore": 0,
        "schedulesAfter": 4,
        "intermediateStops": True,
        "tariffInfoSelector": [
            {"tariff": "HVV", "tariffRegions": True, "kinds": ["1"]},
            {"tariff": "SH", "tariffRegions": False, "kinds": ["1"]},
        ],
        "penalties": [
            {
                "name": "desiredType",
                "value": "akn,r,re,longdistancebus,ast,fasttrain&extrafasttrain:10000",
            }
        ],
        "returnContSearchData": True,
        "realtime": "REALTIME",
    },
    {
        "version": 36,
        "language": "de",
        "start": {
            "name": "Modering",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:86004",
        },
        "via": {
            "name": "Hauptbahnhof",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:9910910",
        },
        "dest": {
            "name": "Stade",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:8000089",
        },
        "toStartBy": "BICYCLE",
        "toDestBy": "FOOTPATH",
        "time": {"date": "13.02.2020", "time": "14:24"},
        "timeIsDeparture": True,
        "schedulesBefore": 0,
        "schedulesAfter": 4,
        "intermediateStops": True,
        "tariffInfoSelector": [
            {"tariff": "HVV", "tariffRegions": True, "kinds": ["1"]},
            {"tariff": "SH", "tariffRegions": False, "kinds": ["1"]},
        ],
        "penalties": [
            {
                "name": "desiredType",
                "value": "akn,r,re,longdistancebus,ast,fasttrain&extrafasttrain:10000",
            },
            {"name": "AnyHandicap", "value": "5"},
            {"name": "ExtraFare", "value": "0"},
            {"name": "DesiredLine", "value": "S1:1"},
        ],
        "returnContSearchData": True,
        "realtime": "REALTIME",
    },
    {
        "version": 36,
        "language": "de",
        "start": {
            "name": "Wartenau",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:10901",
        },
        "via": {
            "name": "Hausbruch",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:41033",
        },
        "dest": {
            "name": "U Ritterstraße",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:60012",
        },
        "forcedStart": {
            "name": "Celsiusweg",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:80114",
        },
        "forcedDest": {
            "name": "Modering",
            "city": "",
            "combinedName": "",
            "type": "STATION",
            "id": "Master:86004",
        },
        "toStartBy": "BICYCLE",
        "toDestBy": "FOOTPATH",
        "time": {"date": "15.02.2020", "time": "15:38"},
        "timeIsDeparture": True,
        "schedulesBefore": 0,
        "schedulesAfter": 4,
        "intermediateStops": True,
        "tariffInfoSelector": [
            {"tariff": "HVV", "tariffRegions": True, "kinds": ["1"]},
            {"tariff": "SH", "tariffRegions": False, "kinds": ["1"]},
        ],
        "penalties": [
            {
                "name": "desiredType",
                "value": "longdistancebus,fasttrain&extrafasttrain:10000",
            },
            {"name": "AnyHandicap", "value": "-1"},
            {"name": "ChangeEvent", "value": "0"},
            {"name": "Walker", "value": "0"},
            {"name": "ExtraFare", "value": "0"},
            {"name": "DesiredLine", "value": "A1:1"},
        ],
        "returnContSearchData": True,
        "realtime": "REALTIME",
    },
]
