# generated by scripts/codegen.py:

from .auth import Auth
from .models import (PCRequest, InitRequest, InitResponse, LLResponse, DLResponse, TariffMetaDataRequest, StationInformationRequest, TariffResponse, PCResponse, CNRequest, CNResponse, GRResponse, IndividualRouteResponse, LSResponse, TariffZoneNeighboursRequest, TicketListRequest, LSRequest, TrackCoordinatesResponse, TariffRequest, SingleTicketOptimizerRequest, VehicleMapResponse, DCRequest, StationInformationResponse, TrackCoordinatesRequest, TariffMetaDataResponse, VehicleMapRequest, DLRequest, TicketListResponse, AnnouncementResponse, IndividualRouteRequest, AnnouncementRequest, TariffZoneNeighboursResponse, SingleTicketOptimizerResponse, DCResponse, LLRequest, GRRequest)

class GTI:
    def __init__(self, auth: Auth):
        self.auth = auth


    async def ticketList(self, payload: TicketListRequest) -> TicketListResponse:
        response = await self.auth.request("post", "/gti/public/ticketList", payload)
        return TicketListResponse.model_validate(response)


    async def tariffZoneNeighbours(self, payload: TariffZoneNeighboursRequest) -> TariffZoneNeighboursResponse:
        response = await self.auth.request("post", "/gti/public/tariffZoneNeighbours", payload)
        return TariffZoneNeighboursResponse.model_validate(response)


    async def tariffMetaData(self, payload: TariffMetaDataRequest) -> TariffMetaDataResponse:
        response = await self.auth.request("post", "/gti/public/tariffMetaData", payload)
        return TariffMetaDataResponse.model_validate(response)


    async def singleTicketOptimizer(self, payload: SingleTicketOptimizerRequest) -> SingleTicketOptimizerResponse:
        response = await self.auth.request("post", "/gti/public/singleTicketOptimizer", payload)
        return SingleTicketOptimizerResponse.model_validate(response)


    async def listStations(self, payload: LSRequest) -> LSResponse:
        response = await self.auth.request("post", "/gti/public/listStations", payload)
        return LSResponse.model_validate(response)


    async def listLines(self, payload: LLRequest) -> LLResponse:
        response = await self.auth.request("post", "/gti/public/listLines", payload)
        return LLResponse.model_validate(response)


    async def init(self, payload: InitRequest) -> InitResponse:
        response = await self.auth.request("post", "/gti/public/init", payload)
        return InitResponse.model_validate(response)


    async def getVehicleMapPublic(self, payload: VehicleMapRequest) -> VehicleMapResponse:
        response = await self.auth.request("post", "/gti/public/getVehicleMap", payload)
        return VehicleMapResponse.model_validate(response)


    async def getTrackCoordinatesPublic(self, payload: TrackCoordinatesRequest) -> TrackCoordinatesResponse:
        response = await self.auth.request("post", "/gti/public/getTrackCoordinates", payload)
        return TrackCoordinatesResponse.model_validate(response)


    async def getTariff(self, payload: TariffRequest) -> TariffResponse:
        response = await self.auth.request("post", "/gti/public/getTariff", payload)
        return TariffResponse.model_validate(response)


    async def getStationInformation(self, payload: StationInformationRequest) -> StationInformationResponse:
        response = await self.auth.request("post", "/gti/public/getStationInformation", payload)
        return StationInformationResponse.model_validate(response)


    async def getRoute(self, payload: GRRequest) -> GRResponse:
        response = await self.auth.request("post", "/gti/public/getRoute", payload)
        return GRResponse.model_validate(response)


    async def getIndividualRoute(self, payload: IndividualRouteRequest) -> IndividualRouteResponse:
        response = await self.auth.request("post", "/gti/public/getIndividualRoute", payload)
        return IndividualRouteResponse.model_validate(response)


    async def getAnnouncements(self, payload: AnnouncementRequest) -> AnnouncementResponse:
        response = await self.auth.request("post", "/gti/public/getAnnouncements", payload)
        return AnnouncementResponse.model_validate(response)


    async def departureList(self, payload: DLRequest) -> DLResponse:
        response = await self.auth.request("post", "/gti/public/departureList", payload)
        return DLResponse.model_validate(response)


    async def departureCourse(self, payload: DCRequest) -> DCResponse:
        response = await self.auth.request("post", "/gti/public/departureCourse", payload)
        return DCResponse.model_validate(response)


    async def checkPostalCode(self, payload: PCRequest) -> PCResponse:
        response = await self.auth.request("post", "/gti/public/checkPostalCode", payload)
        return PCResponse.model_validate(response)


    async def checkName(self, payload: CNRequest) -> CNResponse:
        response = await self.auth.request("post", "/gti/public/checkName", payload)
        return CNResponse.model_validate(response)

