# generated by scripts/codegen.py:

from .auth import Auth
from .models import (
    TariffMetaDataResponse,
    DLRequest,
    CNResponse,
    LSResponse,
    DCResponse,
    DCRequest,
    InitRequest,
    TariffZoneNeighboursResponse,
    IndividualRouteRequest,
    TariffZoneNeighboursRequest,
    LLRequest,
    VehicleMapResponse,
    SingleTicketOptimizerResponse,
    TrackCoordinatesResponse,
    LSRequest,
    GRResponse,
    IndividualRouteResponse,
    VehicleMapRequest,
    StationInformationResponse,
    PCRequest,
    TariffMetaDataRequest,
    TariffRequest,
    TicketListRequest,
    AnnouncementRequest,
    TrackCoordinatesRequest,
    GRRequest,
    InitResponse,
    TariffResponse,
    LLResponse,
    AnnouncementResponse,
    PCResponse,
    StationInformationRequest,
    SingleTicketOptimizerRequest,
    TicketListResponse,
    DLResponse,
    CNRequest,
)

_GTI_PROTOCOL_VERSION = 63


class GTI:
    def __init__(self, auth: Auth, language: str = "de"):
        self.auth = auth
        self.language = language

    async def ticketList(self, payload: TicketListRequest) -> TicketListResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/ticketList",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return TicketListResponse.model_validate(response)

    async def tariffZoneNeighbours(
        self, payload: TariffZoneNeighboursRequest
    ) -> TariffZoneNeighboursResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/tariffZoneNeighbours",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return TariffZoneNeighboursResponse.model_validate(response)

    async def tariffMetaData(
        self, payload: TariffMetaDataRequest
    ) -> TariffMetaDataResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/tariffMetaData",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return TariffMetaDataResponse.model_validate(response)

    async def singleTicketOptimizer(
        self, payload: SingleTicketOptimizerRequest
    ) -> SingleTicketOptimizerResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/singleTicketOptimizer",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return SingleTicketOptimizerResponse.model_validate(response)

    async def listStations(self, payload: LSRequest) -> LSResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/listStations",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return LSResponse.model_validate(response)

    async def listLines(self, payload: LLRequest) -> LLResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/listLines",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return LLResponse.model_validate(response)

    async def init(self, payload: InitRequest) -> InitResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/init",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return InitResponse.model_validate(response)

    async def getVehicleMapPublic(
        self, payload: VehicleMapRequest
    ) -> VehicleMapResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/getVehicleMap",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return VehicleMapResponse.model_validate(response)

    async def getTrackCoordinatesPublic(
        self, payload: TrackCoordinatesRequest
    ) -> TrackCoordinatesResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/getTrackCoordinates",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return TrackCoordinatesResponse.model_validate(response)

    async def getTariff(self, payload: TariffRequest) -> TariffResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/getTariff",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return TariffResponse.model_validate(response)

    async def getStationInformation(
        self, payload: StationInformationRequest
    ) -> StationInformationResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/getStationInformation",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return StationInformationResponse.model_validate(response)

    async def getRoute(self, payload: GRRequest) -> GRResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/getRoute",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return GRResponse.model_validate(response)

    async def getIndividualRoute(
        self, payload: IndividualRouteRequest
    ) -> IndividualRouteResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/getIndividualRoute",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return IndividualRouteResponse.model_validate(response)

    async def getAnnouncements(
        self, payload: AnnouncementRequest
    ) -> AnnouncementResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/getAnnouncements",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return AnnouncementResponse.model_validate(response)

    async def departureList(self, payload: DLRequest) -> DLResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/departureList",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return DLResponse.model_validate(response)

    async def departureCourse(self, payload: DCRequest) -> DCResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/departureCourse",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return DCResponse.model_validate(response)

    async def checkPostalCode(self, payload: PCRequest) -> PCResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/checkPostalCode",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return PCResponse.model_validate(response)

    async def checkName(self, payload: CNRequest) -> CNResponse:
        response = await self.auth.request(
            "post",
            "/gti/public/checkName",
            payload,
            language=self.language,
            version=_GTI_PROTOCOL_VERSION,
        )
        return CNResponse.model_validate(response)
