# generated by datamodel-codegen:
#   filename:  https://gti.geofox.de/v3/api-docs/public
#   timestamp: 2026-04-01T21:21:45+00:00

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, Field
from enum import Enum
from datetime import date as date_aliased


class TicketListRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    stationKey: str | None = None


class PersonInfoPersonType(Enum):
    ALL = 'ALL'
    ELDERLY = 'ELDERLY'
    APPRENTICE = 'APPRENTICE'
    PUPIL = 'PUPIL'
    STUDENT = 'STUDENT'
    CHILD = 'CHILD'


class PersonInfo(BaseModel):
    personType: PersonInfoPersonType | None = None
    personCount: int | None = None


class TicketListTicketInfosRegionType(Enum):
    ZONE = 'ZONE'
    GH_ZONE = 'GH_ZONE'
    RING = 'RING'
    COUNTY = 'COUNTY'
    GH = 'GH'
    NET = 'NET'
    ZG = 'ZG'
    STADTVERKEHR = 'STADTVERKEHR'


class TicketListTicketVariantTicketClass(Enum):
    NONE = 'NONE'
    SECOND = 'SECOND'
    FIRST = 'FIRST'
    SCHNELL = 'SCHNELL'


class TicketListTicketVariantDiscount(Enum):
    NONE = 'NONE'
    ONLINE = 'ONLINE'
    SOCIAL = 'SOCIAL'


class TicketListTicketVariant(BaseModel):
    ticketId: int | None = None
    kaNummer: int | None = None
    price: float | None = None
    currency: str | None = 'EUR'
    ticketClass: TicketListTicketVariantTicketClass
    discount: TicketListTicketVariantDiscount
    validityBegin: date_aliased
    validityEnd: date_aliased


class TimePeriod(BaseModel):
    begin: str
    end: str


class ValidityPeriodDay(Enum):
    WEEKDAY = 'WEEKDAY'
    WEEKEND = 'WEEKEND'


class ValidityPeriod(BaseModel):
    day: ValidityPeriodDay
    timeValidities: list[TimePeriod] | None = None


class TariffZoneNeighboursRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1


class TariffZone(BaseModel):
    zone: str
    ring: str
    neighbours: list[str]


class TariffZoneNeighboursResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    tariffZones: list[TariffZone]


class TariffMetaDataRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1


class RequiredRegionTypeType(Enum):
    ZONE = 'ZONE'
    GH_ZONE = 'GH_ZONE'
    RING = 'RING'
    COUNTY = 'COUNTY'
    GH = 'GH'
    NET = 'NET'
    ZG = 'ZG'
    STADTVERKEHR = 'STADTVERKEHR'


class RequiredRegionType(BaseModel):
    type: RequiredRegionTypeType
    count: int | None = None


class TariffCounty(BaseModel):
    id: str
    label: str


class TariffKindTicketType(Enum):
    OCCASIONAL_TICKET = 'OCCASIONAL_TICKET'
    SEASON_TICKET = 'SEASON_TICKET'


class TariffKind(BaseModel):
    id: int | None = None
    label: str
    requiresPersonType: bool | None = False
    ticketType: TariffKindTicketType | None = None
    levelCombinations: list[int] | None = None


class TariffLevel(BaseModel):
    id: int | None = None
    label: str
    requiredRegionType: RequiredRegionType


class TariffMetaDataResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    tariffKinds: list[TariffKind] | None = None
    tariffLevels: list[TariffLevel] | None = None
    tariffCounties: list[TariffCounty] | None = None
    tariffZones: list[TariffZone] | None = None
    tariffRings: list[str] | None = None


class SingleTicketOptimizerRequestLine(BaseModel):
    id: str
    name: str


class SingleTicketOptimizerRequestRouteExtraFareType(Enum):
    NO = 'NO'
    POSSIBLE = 'POSSIBLE'
    REQUIRED = 'REQUIRED'


class SingleTicketOptimizerRequestStation(BaseModel):
    id: str
    name: str


class SingleTicketOptimizerRequestTrip(BaseModel):
    start: SingleTicketOptimizerRequestStation
    destination: SingleTicketOptimizerRequestStation
    line: SingleTicketOptimizerRequestLine
    vehicleType: str


class TariffOptimizerTicketRegionType(Enum):
    RING = 'RING'
    ZONE = 'ZONE'
    COUNTY = 'COUNTY'
    GH_ZONE = 'GH_ZONE'


class TariffOptimizerTicketPersonType(Enum):
    ALL = 'ALL'
    ADULT = 'ADULT'
    ELDERLY = 'ELDERLY'
    APPRENTICE = 'APPRENTICE'
    PUPIL = 'PUPIL'
    STUDENT = 'STUDENT'
    CHILD = 'CHILD'


class TariffOptimizerTicket(BaseModel):
    tariffKindId: int | None = None
    tariffKindLabel: str | None = None
    tariffLevelId: int | None = None
    tariffLevelLabel: str | None = None
    tariffRegions: list[str]
    regionType: TariffOptimizerTicketRegionType
    count: int | None = None
    extraFare: bool | None = None
    personType: TariffOptimizerTicketPersonType
    centPrice: int | None = None


class TariffRegions(BaseModel):
    regions: list[str]


class SingleTicketOptimizerResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    tickets: list[TariffOptimizerTicket] | None = None


class LSRequestModificationType(Enum):
    MAIN = 'MAIN'
    POSITION = 'POSITION'


class LSRequestCoordinateType(Enum):
    EPSG_4326 = 'EPSG_4326'
    EPSG_31466 = 'EPSG_31466'
    EPSG_31467 = 'EPSG_31467'
    EPSG_31468 = 'EPSG_31468'
    EPSG_31469 = 'EPSG_31469'


class LSRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    dataReleaseID: str | None = None
    modificationTypes: list[LSRequestModificationType] | None = None
    coordinateType: LSRequestCoordinateType | None = 'EPSG_4326'
    filterEquivalent: bool | None = False


class CoordinateType(Enum):
    EPSG_4326 = 'EPSG_4326'
    EPSG_31466 = 'EPSG_31466'
    EPSG_31467 = 'EPSG_31467'
    EPSG_31468 = 'EPSG_31468'
    EPSG_31469 = 'EPSG_31469'


class Coordinate(BaseModel):
    x: float | None = None
    y: float | None = None
    type: CoordinateType | None = 'EPSG_4326'


class StationListEntryVehicleType(Enum):
    REGIONALBUS = 'REGIONALBUS'
    METROBUS = 'METROBUS'
    NACHTBUS = 'NACHTBUS'
    SCHNELLBUS = 'SCHNELLBUS'
    XPRESSBUS = 'XPRESSBUS'
    AST = 'AST'
    SCHIFF = 'SCHIFF'
    U_BAHN = 'U_BAHN'
    S_BAHN = 'S_BAHN'
    A_BAHN = 'A_BAHN'
    R_BAHN = 'R_BAHN'
    F_BAHN = 'F_BAHN'
    EILBUS = 'EILBUS'


class StationListEntry(BaseModel):
    id: str
    name: str | None = None
    city: str | None = None
    combinedName: str | None = None
    shortcuts: list[str] | None = None
    aliasses: list[str] | None = None
    vehicleTypes: list[StationListEntryVehicleType] | None = None
    coordinate: Coordinate | None = None
    exists: bool | None = True


class LLRequestModificationType(Enum):
    MAIN = 'MAIN'
    SEQUENCE = 'SEQUENCE'


class LLRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    withSublines: bool | None = None
    dataReleaseID: str | None = None
    modificationTypes: list[LLRequestModificationType] | None = None


class ServiceTypeSimpleType(Enum):
    BUS = 'BUS'
    TRAIN = 'TRAIN'
    SHIP = 'SHIP'
    FOOTPATH = 'FOOTPATH'
    BICYCLE = 'BICYCLE'
    AIRPLANE = 'AIRPLANE'
    CHANGE = 'CHANGE'
    CHANGE_SAME_PLATFORM = 'CHANGE_SAME_PLATFORM'
    ACTIVITY_BIKE_AND_RIDE = 'ACTIVITY_BIKE_AND_RIDE'


class ServiceType(BaseModel):
    simpleType: ServiceTypeSimpleType
    shortInfo: str | None = None
    longInfo: str | None = None
    model: str | None = None


class StationLight(BaseModel):
    id: str
    name: str | None = None


class SublineListEntryVehicleType(Enum):
    REGIONALBUS = 'REGIONALBUS'
    METROBUS = 'METROBUS'
    NACHTBUS = 'NACHTBUS'
    SCHNELLBUS = 'SCHNELLBUS'
    XPRESSBUS = 'XPRESSBUS'
    AST = 'AST'
    SCHIFF = 'SCHIFF'
    U_BAHN = 'U_BAHN'
    S_BAHN = 'S_BAHN'
    A_BAHN = 'A_BAHN'
    R_BAHN = 'R_BAHN'
    F_BAHN = 'F_BAHN'
    EILBUS = 'EILBUS'


class SublineListEntry(BaseModel):
    sublineNumber: str
    vehicleType: SublineListEntryVehicleType
    stationSequence: list[StationLight] | None = None


class Property(BaseModel):
    key: str
    value: str | None = None


class InitResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    beginOfService: str
    endOfService: str
    id: str
    dataId: str
    buildDate: str
    buildTime: str
    buildText: str
    version: str
    properties: list[Property] | None = None


class BoundingBox(BaseModel):
    lowerLeft: Coordinate
    upperRight: Coordinate


class VehicleMapRequestCoordinateType(Enum):
    EPSG_4326 = 'EPSG_4326'
    EPSG_31466 = 'EPSG_31466'
    EPSG_31467 = 'EPSG_31467'
    EPSG_31468 = 'EPSG_31468'
    EPSG_31469 = 'EPSG_31469'


class VehicleMapRequestVehicleType(Enum):
    REGIONALBUS = 'REGIONALBUS'
    METROBUS = 'METROBUS'
    NACHTBUS = 'NACHTBUS'
    SCHNELLBUS = 'SCHNELLBUS'
    XPRESSBUS = 'XPRESSBUS'
    AST = 'AST'
    SCHIFF = 'SCHIFF'
    U_BAHN = 'U_BAHN'
    S_BAHN = 'S_BAHN'
    A_BAHN = 'A_BAHN'
    R_BAHN = 'R_BAHN'
    F_BAHN = 'F_BAHN'
    EILBUS = 'EILBUS'


class VehicleMapRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    boundingBox: BoundingBox
    periodBegin: int | None = None
    periodEnd: int | None = None
    withoutCoords: bool | None = None
    coordinateType: VehicleMapRequestCoordinateType | None = 'EPSG_4326'
    vehicleTypes: list[VehicleMapRequestVehicleType] | None = None
    realtime: bool | None = None


class JourneyVehicleType(Enum):
    REGIONALBUS = 'REGIONALBUS'
    METROBUS = 'METROBUS'
    NACHTBUS = 'NACHTBUS'
    SCHNELLBUS = 'SCHNELLBUS'
    XPRESSBUS = 'XPRESSBUS'
    AST = 'AST'
    SCHIFF = 'SCHIFF'
    U_BAHN = 'U_BAHN'
    S_BAHN = 'S_BAHN'
    A_BAHN = 'A_BAHN'
    R_BAHN = 'R_BAHN'
    F_BAHN = 'F_BAHN'
    EILBUS = 'EILBUS'


class Service(BaseModel):
    name: str
    direction: str | None = None
    directionId: int | None = None
    origin: str | None = None
    type: ServiceType
    id: str | None = None
    dlid: str | None = None
    carrierNameShort: str | None = None
    carrierNameLong: str | None = None


class VehicleMapPathCoordinateType(Enum):
    EPSG_4326 = 'EPSG_4326'
    EPSG_31466 = 'EPSG_31466'
    EPSG_31467 = 'EPSG_31467'
    EPSG_31468 = 'EPSG_31468'
    EPSG_31469 = 'EPSG_31469'


class VehicleMapPath(BaseModel):
    track: list[float] | None = None
    coordinateType: VehicleMapPathCoordinateType


class TrackCoordinatesRequestCoordinateType(Enum):
    EPSG_4326 = 'EPSG_4326'
    EPSG_31466 = 'EPSG_31466'
    EPSG_31467 = 'EPSG_31467'
    EPSG_31468 = 'EPSG_31468'
    EPSG_31469 = 'EPSG_31469'


class TrackCoordinatesRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    coordinateType: TrackCoordinatesRequestCoordinateType | None = 'EPSG_4326'
    stopPointKeys: list[str]


class TrackCoordinatesResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    trackIDs: list[str]
    tracks: list[VehicleMapPath]


class GTITime(BaseModel):
    date: str
    time: str


class ScheduleElementLight(BaseModel):
    departureStationId: str
    arrivalStationId: str
    intermediateStops: list[str] | None = None
    lineId: str


class TariffInfoSelector(BaseModel):
    tariff: str | None = 'HVV'
    tariffRegions: bool | None = True
    kinds: list[int] | None = None
    groups: list[int] | None = None
    blacklist: bool | None = False


class TariffRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    scheduleElements: list[ScheduleElementLight]
    departure: GTITime
    arrival: GTITime
    returnReduced: bool | None = False
    returnPartialTickets: bool | None = True
    tariffInfoSelector: list[TariffInfoSelector] | None = None


class TariffInfoExtraFareType(Enum):
    NO = 'NO'
    POSSIBLE = 'POSSIBLE'
    REQUIRED = 'REQUIRED'


class TariffRegionInfoRegionType(Enum):
    ZONE = 'ZONE'
    GH_ZONE = 'GH_ZONE'
    RING = 'RING'
    COUNTY = 'COUNTY'
    GH = 'GH'
    NET = 'NET'
    ZG = 'ZG'
    STADTVERKEHR = 'STADTVERKEHR'


class TariffRegionList(BaseModel):
    regions: list[str] | None = None


class TicketInfoRegionType(Enum):
    ZONE = 'ZONE'
    GH_ZONE = 'GH_ZONE'
    RING = 'RING'
    COUNTY = 'COUNTY'
    GH = 'GH'
    NET = 'NET'
    ZG = 'ZG'
    STADTVERKEHR = 'STADTVERKEHR'


class TicketInfo(BaseModel):
    tariffKindID: int | None = None
    tariffKindLabel: str
    tariffLevelID: int | None = None
    tariffLevelLabel: str
    tariffGroupID: int | None = None
    tariffGroupLabel: str | None = None
    viaPathId: int | None = None
    basePrice: float | None = None
    extraFarePrice: float | None = None
    reducedBasePrice: float | None = None
    reducedExtraFarePrice: float | None = None
    currency: str | None = 'EUR'
    regionType: TicketInfoRegionType | None = None
    notRecommended: bool | None = False
    shopLinkRegular: str | None = None
    shopLinkExtraFare: str | None = None
    startStationId: str | None = None
    endStationId: str | None = None
    baseTicketID: str | None = None
    reducedBaseTicketID: str | None = None
    extraFareTicketID: str | None = None
    reducedExtraFareTicketID: str | None = None


class SDNameType(Enum):
    UNKNOWN = 'UNKNOWN'
    STATION = 'STATION'
    ADDRESS = 'ADDRESS'
    POI = 'POI'
    COORDINATE = 'COORDINATE'
    BIKE_AND_RIDE = 'BIKE_AND_RIDE'
    STOP_POINT = 'STOP_POINT'


class TariffDetails(BaseModel):
    innerCity: bool | None = None
    city: bool | None = None
    cityTraffic: bool | None = None
    gratis: bool | None = None
    greaterArea: bool | None = None
    shVillageId: int | None = None
    shTariffZone: int | None = None
    tariffZones: list[int] | None = None
    regions: list[int] | None = None
    counties: list[str] | None = None
    rings: list[str] | None = None
    fareStage: bool | None = None
    fareStageNumber: int | None = None
    tariffNames: list[str] | None = None
    uniqueValues: bool | None = None


class ElevatorButtonType(Enum):
    BRAILLE = 'BRAILLE'
    ACUSTIC = 'ACUSTIC'
    COMBI = 'COMBI'
    UNKNOWN = 'UNKNOWN'


class ElevatorState(Enum):
    READY = 'READY'
    OUTOFORDER = 'OUTOFORDER'
    UNKNOWN = 'UNKNOWN'


class Elevator(BaseModel):
    lines: list[str] | None = None
    label: str | None = None
    cabinWidth: int | None = None
    cabinLength: int | None = None
    doorWidth: int | None = None
    description: str | None = None
    elevatorType: str | None = None
    buttonType: ElevatorButtonType | None = None
    state: ElevatorState | None = None
    cause: str | None = None


class PartialStation(BaseModel):
    lines: list[str] | None = None
    stationOutline: str | None = None
    elevators: list[Elevator] | None = None


class StationInformationResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    partialStations: list[PartialStation] | None = None
    lastUpdate: GTITime | None = None


class ContSearchByServiceId(BaseModel):
    serviceId: int | None = None
    lineKey: str
    plannedDepArrTime: GTITime
    additionalOffset: int | None = None


class GRRequestCoordinateType(Enum):
    EPSG_4326 = 'EPSG_4326'
    EPSG_31466 = 'EPSG_31466'
    EPSG_31467 = 'EPSG_31467'
    EPSG_31468 = 'EPSG_31468'
    EPSG_31469 = 'EPSG_31469'


class GRRequestRealtime(Enum):
    PLANDATA = 'PLANDATA'
    REALTIME = 'REALTIME'
    AUTO = 'AUTO'


class GRRequestToStartBy(Enum):
    BUS = 'BUS'
    TRAIN = 'TRAIN'
    SHIP = 'SHIP'
    FOOTPATH = 'FOOTPATH'
    BICYCLE = 'BICYCLE'
    AIRPLANE = 'AIRPLANE'
    CHANGE = 'CHANGE'
    CHANGE_SAME_PLATFORM = 'CHANGE_SAME_PLATFORM'
    ACTIVITY_BIKE_AND_RIDE = 'ACTIVITY_BIKE_AND_RIDE'


class GRRequestToDestBy(Enum):
    BUS = 'BUS'
    TRAIN = 'TRAIN'
    SHIP = 'SHIP'
    FOOTPATH = 'FOOTPATH'
    BICYCLE = 'BICYCLE'
    AIRPLANE = 'AIRPLANE'
    CHANGE = 'CHANGE'
    CHANGE_SAME_PLATFORM = 'CHANGE_SAME_PLATFORM'
    ACTIVITY_BIKE_AND_RIDE = 'ACTIVITY_BIKE_AND_RIDE'


class Penalty(BaseModel):
    name: str
    value: str


class Attribute(BaseModel):
    title: str | None = None
    isPlanned: bool | None = None
    value: str
    types: list[str] | None = None
    id: str | None = None


class IndividualTrackType(Enum):
    BUS = 'BUS'
    TRAIN = 'TRAIN'
    SHIP = 'SHIP'
    FOOTPATH = 'FOOTPATH'
    BICYCLE = 'BICYCLE'
    AIRPLANE = 'AIRPLANE'
    CHANGE = 'CHANGE'
    CHANGE_SAME_PLATFORM = 'CHANGE_SAME_PLATFORM'
    ACTIVITY_BIKE_AND_RIDE = 'ACTIVITY_BIKE_AND_RIDE'


class IndividualTrack(BaseModel):
    time: int | None = None
    length: int | None = None
    type: IndividualTrackType


class JourneySDNameType(Enum):
    UNKNOWN = 'UNKNOWN'
    STATION = 'STATION'
    ADDRESS = 'ADDRESS'
    POI = 'POI'
    COORDINATE = 'COORDINATE'
    BIKE_AND_RIDE = 'BIKE_AND_RIDE'
    STOP_POINT = 'STOP_POINT'


class JourneySDName(BaseModel):
    name: str | None = None
    city: str | None = None
    combinedName: str | None = None
    id: str | None = None
    globalId: str | None = None
    provider: str | None = None
    type: JourneySDNameType | None = 'UNKNOWN'
    coordinate: Coordinate | None = None
    layer: int | None = None
    tariffDetails: TariffDetails | None = None
    serviceTypes: list[str] | None = None
    hasStationInformation: bool | None = None
    address: str | None = None
    arrTime: GTITime | None = None
    depTime: GTITime | None = None
    arrDelay: int | None = None
    depDelay: int | None = None
    extra: bool | None = False
    cancelled: bool | None = False
    attributes: list[Attribute] | None = None
    platform: str | None = None
    realtimePlatform: str | None = None


class Link(BaseModel):
    label: str
    url: str


class LocationType(Enum):
    SINGLE_LINE = 'SINGLE_LINE'
    ALL_LINES_OF_CARRIER = 'ALL_LINES_OF_CARRIER'
    COMPLETE_NET = 'COMPLETE_NET'


class MapEntry(BaseModel):
    key: str
    value: str


class Path(BaseModel):
    track: list[Coordinate]
    attributes: list[str] | None = None
    tags: list[MapEntry] | None = None


class ShopInfoShopType(Enum):
    AST = 'AST'


class ShopInfo(BaseModel):
    shopType: ShopInfoShopType
    url: str


class Ticket(BaseModel):
    price: float | None = None
    reducedPrice: float | None = None
    currency: str | None = 'EUR'
    type: str
    level: str
    tariff: str
    range: str | None = None
    ticketRemarks: str | None = None


class TimeRange(BaseModel):
    begin: AwareDatetime | None = None
    end: AwareDatetime | None = None


class Vehicle(BaseModel):
    id: str | None = None
    number: str | None = None


class IndividualRouteRequestType(Enum):
    EPSG_4326 = 'EPSG_4326'
    EPSG_31466 = 'EPSG_31466'
    EPSG_31467 = 'EPSG_31467'
    EPSG_31468 = 'EPSG_31468'
    EPSG_31469 = 'EPSG_31469'


class IndividualRouteRequestServiceType(Enum):
    BUS = 'BUS'
    TRAIN = 'TRAIN'
    SHIP = 'SHIP'
    FOOTPATH = 'FOOTPATH'
    BICYCLE = 'BICYCLE'
    AIRPLANE = 'AIRPLANE'
    CHANGE = 'CHANGE'
    CHANGE_SAME_PLATFORM = 'CHANGE_SAME_PLATFORM'
    ACTIVITY_BIKE_AND_RIDE = 'ACTIVITY_BIKE_AND_RIDE'


class IndividualRouteRequestProfile(Enum):
    BICYCLE_NORMAL = 'BICYCLE_NORMAL'
    BICYCLE_RACING = 'BICYCLE_RACING'
    BICYCLE_QUIET_ROADS = 'BICYCLE_QUIET_ROADS'
    BICYCLE_MAIN_ROADS = 'BICYCLE_MAIN_ROADS'
    BICYCLE_BAD_WEATHER = 'BICYCLE_BAD_WEATHER'
    FOOT_NORMAL = 'FOOT_NORMAL'


class IndividualRouteServiceType(Enum):
    BUS = 'BUS'
    TRAIN = 'TRAIN'
    SHIP = 'SHIP'
    FOOTPATH = 'FOOTPATH'
    BICYCLE = 'BICYCLE'
    AIRPLANE = 'AIRPLANE'
    CHANGE = 'CHANGE'
    CHANGE_SAME_PLATFORM = 'CHANGE_SAME_PLATFORM'
    ACTIVITY_BIKE_AND_RIDE = 'ACTIVITY_BIKE_AND_RIDE'


class AnnouncementRequestFilterPlanned(Enum):
    NO_FILTER = 'NO_FILTER'
    ONLY_PLANNED = 'ONLY_PLANNED'
    ONLY_UNPLANNED = 'ONLY_UNPLANNED'


class AnnouncementRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    names: list[str] | None = None
    timeRange: TimeRange | None = None
    full: bool | None = False
    filterPlanned: AnnouncementRequestFilterPlanned | None = None
    showBroadcastRelevant: bool | None = False


class DLFilterEntry(BaseModel):
    serviceID: str | None = None
    stationIDs: list[str] | None = None
    label: str | None = None
    serviceName: str | None = None


class DLRequestServiceType(Enum):
    ZUG = 'ZUG'
    UBAHN = 'UBAHN'
    SBAHN = 'SBAHN'
    AKN = 'AKN'
    RBAHN = 'RBAHN'
    FERNBAHN = 'FERNBAHN'
    BUS = 'BUS'
    STADTBUS = 'STADTBUS'
    METROBUS = 'METROBUS'
    SCHNELLBUS = 'SCHNELLBUS'
    NACHTBUS = 'NACHTBUS'
    XPRESSBUS = 'XPRESSBUS'
    EILBUS = 'EILBUS'
    AST = 'AST'
    FAEHRE = 'FAEHRE'


class DLRequestCoordinateType(Enum):
    EPSG_4326 = 'EPSG_4326'
    EPSG_31466 = 'EPSG_31466'
    EPSG_31467 = 'EPSG_31467'
    EPSG_31468 = 'EPSG_31468'
    EPSG_31469 = 'EPSG_31469'


class DLResponseServiceType(Enum):
    ZUG = 'ZUG'
    UBAHN = 'UBAHN'
    SBAHN = 'SBAHN'
    AKN = 'AKN'
    RBAHN = 'RBAHN'
    FERNBAHN = 'FERNBAHN'
    BUS = 'BUS'
    STADTBUS = 'STADTBUS'
    METROBUS = 'METROBUS'
    SCHNELLBUS = 'SCHNELLBUS'
    NACHTBUS = 'NACHTBUS'
    XPRESSBUS = 'XPRESSBUS'
    EILBUS = 'EILBUS'
    AST = 'AST'
    FAEHRE = 'FAEHRE'


class DCRequestSegments(Enum):
    BEFORE = 'BEFORE'
    AFTER = 'AFTER'
    ALL = 'ALL'


class DCRequestCoordinateType(Enum):
    EPSG_4326 = 'EPSG_4326'
    EPSG_31466 = 'EPSG_31466'
    EPSG_31467 = 'EPSG_31467'
    EPSG_31468 = 'EPSG_31468'
    EPSG_31469 = 'EPSG_31469'


class PCRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    postalCode: int | None = None


class PCResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    isHVV: bool | None = None


class CNRequestCoordinateType(Enum):
    EPSG_4326 = 'EPSG_4326'
    EPSG_31466 = 'EPSG_31466'
    EPSG_31467 = 'EPSG_31467'
    EPSG_31468 = 'EPSG_31468'
    EPSG_31469 = 'EPSG_31469'


class RegionalSDNameType(Enum):
    UNKNOWN = 'UNKNOWN'
    STATION = 'STATION'
    ADDRESS = 'ADDRESS'
    POI = 'POI'
    COORDINATE = 'COORDINATE'
    BIKE_AND_RIDE = 'BIKE_AND_RIDE'
    STOP_POINT = 'STOP_POINT'


class RegionalSDName(BaseModel):
    name: str | None = None
    city: str | None = None
    combinedName: str | None = None
    id: str | None = None
    globalId: str | None = None
    provider: str | None = None
    type: RegionalSDNameType | None = 'UNKNOWN'
    coordinate: Coordinate | None = None
    layer: int | None = None
    tariffDetails: TariffDetails | None = None
    serviceTypes: list[str] | None = None
    hasStationInformation: bool | None = None
    address: str | None = None
    distance: int | None = None
    time: int | None = None


class TicketListTicketInfos(BaseModel):
    tariffKindID: int | None = None
    tariffKindLabel: str
    tariffLevelID: int | None = None
    tariffLevelLabel: str
    tariffGroupID: int | None = None
    tariffGroupLabel: str | None = None
    regionType: TicketListTicketInfosRegionType | None = None
    selectableRegions: int | None = 0
    requiredStartStation: bool | None = False
    personInfos: list[PersonInfo] | None = None
    validityPeriods: list[ValidityPeriod] | None = None
    variants: list[TicketListTicketVariant] | None = None


class TariffOptimizerRegions(BaseModel):
    zones: list[TariffRegions] | None = None
    rings: list[TariffRegions] | None = None
    counties: list[TariffRegions] | None = None


class LSResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    dataReleaseID: str | None = None
    stations: list[StationListEntry] | None = None


class LineListEntry(BaseModel):
    id: str
    name: str | None = None
    carrierNameShort: str | None = None
    carrierNameLong: str | None = None
    sublines: list[SublineListEntry] | None = None
    exists: bool | None = True
    type: ServiceType


class InitRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    properties: list[Property] | None = None


class PathSegment(BaseModel):
    startStopPointKey: str
    endStopPointKey: str
    startStationName: str
    startStationKey: str
    startDateTime: int | None = None
    endStationName: str
    endStationKey: str
    endDateTime: int | None = None
    track: VehicleMapPath
    destination: str
    realtimeDelay: int | None = None
    isFirst: bool | None = None
    isLast: bool | None = None


class TariffRegionInfo(BaseModel):
    regionType: TariffRegionInfoRegionType
    alternatives: list[TariffRegionList] | None = None


class SDName(BaseModel):
    name: str | None = None
    city: str | None = None
    combinedName: str | None = None
    id: str | None = None
    globalId: str | None = None
    provider: str | None = None
    type: SDNameType | None = 'UNKNOWN'
    coordinate: Coordinate | None = None
    layer: int | None = None
    tariffDetails: TariffDetails | None = None
    serviceTypes: list[str] | None = None
    hasStationInformation: bool | None = None
    address: str | None = None


class StationInformationRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    station: SDName


class GRRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    start: SDName
    dest: SDName
    via: SDName | None = None
    time: GTITime
    timeIsDeparture: bool | None = None
    withPaths: bool | None = None
    numberOfSchedules: int | None = None
    penalties: list[Penalty] | None = None
    tariffDetails: bool | None = False
    continousSearch: bool | None = False
    contSearchByServiceId: ContSearchByServiceId | None = None
    coordinateType: GRRequestCoordinateType | None = 'EPSG_4326'
    schedulesBefore: int | None = 0
    schedulesAfter: int | None = 0
    tariffInfoSelector: list[TariffInfoSelector] | None = None
    returnReduced: bool | None = False
    returnPartialTickets: bool | None = True
    realtime: GRRequestRealtime | None = 'AUTO'
    intermediateStops: bool | None = False
    useStationPosition: bool | None = True
    forcedStart: SDName | None = None
    forcedDest: SDName | None = None
    toStartBy: GRRequestToStartBy | None = None
    toDestBy: GRRequestToDestBy | None = None
    returnContSearchData: bool | None = None
    useBikeAndRide: bool | None = False


class Location(BaseModel):
    type: LocationType
    name: str | None = None
    line: Service | None = None
    begin: SDName | None = None
    end: SDName | None = None
    bothDirections: bool | None = True


class IndividualRouteRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    starts: list[SDName]
    dests: list[SDName]
    maxLength: int | None = None
    maxResults: int | None = None
    type: IndividualRouteRequestType | None = 'EPSG_4326'
    serviceType: IndividualRouteRequestServiceType | None = 'FOOTPATH'
    profile: IndividualRouteRequestProfile | None = 'FOOT_NORMAL'
    speed: str | None = 'NORMAL'


class IndividualRoute(BaseModel):
    start: SDName
    dest: SDName
    path: Path | None = None
    paths: list[Path] | None = None
    length: int | None = None
    time: int | None = None
    serviceType: IndividualRouteServiceType


class IndividualRouteResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    routes: list[IndividualRoute]


class DLRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    station: SDName | None = None
    stations: list[SDName] | None = None
    time: GTITime
    maxList: int | None = None
    maxTimeOffset: int | None = 120
    allStationsInChangingNode: bool | None = True
    useRealtime: bool | None = False
    returnFilters: bool | None = False
    filter: list[DLFilterEntry] | None = None
    serviceTypes: list[DLRequestServiceType] | None = None
    departure: bool | None = True
    coordinateType: DLRequestCoordinateType | None = 'EPSG_4326'


class Departure(BaseModel):
    line: Service
    directionId: int | None = None
    timeOffset: int | None = None
    delay: int | None = None
    extra: bool | None = False
    cancelled: bool | None = False
    serviceId: int | None = None
    station: SDName | None = None
    stopPoint: SDName | None = None
    platform: str | None = None
    realtimePlatform: str | None = None
    vehicles: list[Vehicle] | None = None
    attributes: list[Attribute] | None = None


class DCRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    lineKey: str | None = None
    lineId: str | None = None
    station: SDName
    time: AwareDatetime
    direction: str | None = None
    origin: str | None = None
    serviceId: int | None = -1
    segments: DCRequestSegments | None = 'ALL'
    showPath: bool | None = False
    coordinateType: DCRequestCoordinateType | None = 'EPSG_4326'


class CourseElement(BaseModel):
    fromStation: SDName
    fromPlatform: str | None = None
    fromRealtimePlatform: str | None = None
    toStation: SDName
    toPlatform: str | None = None
    toRealtimePlatform: str | None = None
    model: str | None = None
    depTime: AwareDatetime
    arrTime: AwareDatetime
    depDelay: int | None = None
    arrDelay: int | None = None
    fromExtra: bool | None = False
    fromCancelled: bool | None = False
    toExtra: bool | None = False
    toCancelled: bool | None = False
    attributes: list[Attribute] | None = None
    path: Path | None = None


class DCResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    courseElements: list[CourseElement] | None = None
    vehicles: list[Vehicle] | None = None
    extra: bool | None = False
    cancelled: bool | None = False
    attributes: list[Attribute] | None = None


class CNRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    theName: SDName
    maxList: int | None = None
    maxDistance: int | None = None
    coordinateType: CNRequestCoordinateType | None = 'EPSG_4326'
    tariffDetails: bool | None = False
    allowTypeSwitch: bool | None = True


class CNResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    results: list[RegionalSDName] | None = None


class TicketListResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    ticketInfos: list[TicketListTicketInfos]


class SingleTicketOptimizerRequestRoute(BaseModel):
    trip: list[SingleTicketOptimizerRequestTrip]
    departure: AwareDatetime
    arrival: AwareDatetime
    tariffRegions: TariffOptimizerRegions
    singleTicketTariffLevelId: int | None = None
    extraFareType: SingleTicketOptimizerRequestRouteExtraFareType


class LLResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    dataReleaseID: str | None = None
    lines: list[LineListEntry] | None = None


class Journey(BaseModel):
    journeyID: str
    line: Service
    vehicleType: JourneyVehicleType
    realtime: bool | None = None
    segments: list[PathSegment] | None = None


class VehicleMapResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    journeys: list[Journey]


class TariffInfo(BaseModel):
    tariffName: str
    tariffRegions: list[TariffRegionInfo] | None = None
    regionTexts: list[str] | None = None
    extraFareType: TariffInfoExtraFareType | None = 'NO'
    ticketInfos: list[TicketInfo] | None = None
    ticketRemarks: str | None = None


class TariffResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    tariffInfos: list[TariffInfo] | None = None


class Announcement(BaseModel):
    id: str | None = None
    version: int | None = None
    summary: str | None = None
    locations: list[Location] | None = None
    description: str
    links: list[Link] | None = None
    publication: TimeRange
    validities: list[TimeRange]
    lastModified: AwareDatetime
    planned: bool | None = None
    reason: str | None = None
    broadcastRelevant: bool | None = None


class ScheduleElement(BaseModel):
    from_: JourneySDName = Field(..., alias='from')
    to: JourneySDName
    line: Service
    paths: list[Path] | None = None
    attributes: list[Attribute] | None = None
    announcements: list[Announcement] | None = None
    extra: bool | None = False
    cancelled: bool | None = False
    intermediateStops: list[JourneySDName] | None = None
    vehicles: list[Vehicle] | None = None
    serviceId: int | None = None
    shopInfo: list[ShopInfo] | None = None


class AnnouncementResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    announcements: list[Announcement] | None = None
    lastUpdate: AwareDatetime


class DLResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    time: GTITime
    departures: list[Departure] | None = None
    filter: list[DLFilterEntry] | None = None
    serviceTypes: list[DLResponseServiceType] | None = None


class SingleTicketOptimizerRequest(BaseModel):
    language: str | None = 'de'
    version: int | None = 1
    withReturnJourney: bool | None = None
    numberOfAdults: int | None = None
    numberOfChildren: int | None = None
    tickets: list[TariffOptimizerTicket] | None = None
    route: SingleTicketOptimizerRequestRoute


class Schedule(BaseModel):
    routeId: int | None = None
    start: SDName
    dest: SDName
    time: int | None = None
    footpathTime: int | None = None
    plannedDepartureTime: AwareDatetime | None = None
    realDepartureTime: AwareDatetime | None = None
    plannedArrivalTime: AwareDatetime | None = None
    realArrivalTime: AwareDatetime | None = None
    tickets: list[Ticket] | None = None
    tariffInfos: list[TariffInfo] | None = None
    scheduleElements: list[ScheduleElement] | None = None
    contSearchBefore: ContSearchByServiceId | None = None
    contSearchAfter: ContSearchByServiceId | None = None


class GRResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None
    schedules: list[Schedule] | None = None
    realtimeSchedules: list[Schedule] | None = None
    realtimeAffected: bool | None = False
    individualTrack: IndividualTrack | None = None
