import urllib.request
import json
import keyword
import subprocess
from graphlib import TopologicalSorter
from typing import Any

SPEC_URL = "https://gti.geofox.de/v3/api-docs/public"
GTI_PROTOCOL_VERSION = 63

MODELS_HEADER = """# generated by scripts/codegen.py:
#   filename:  https://gti.geofox.de/v3/api-docs/public

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, Field
from enum import Enum
from datetime import date as date_aliased


class ReturnCode(str, Enum):
    OK = "OK"
    ERROR_CN_TOO_MANY = "ERROR_CN_TOO_MANY"
    ERROR_COMM = "ERROR_COMM"
    ERROR_ROUTE = "ERROR_ROUTE"
    ERROR_TEXT = "ERROR_TEXT"
    START_NOT_FOUND = "START_NOT_FOUND"
    DEST_NOT_FOUND = "DEST_NOT_FOUND"
    VIA_NOT_FOUND = "VIA_NOT_FOUND"
    FORCED_START_NOT_FOUND = "FORCED_START_NOT_FOUND"
    FORCED_DEST_NOT_FOUND = "FORCED_DEST_NOT_FOUND"


class GTIResponse(BaseModel):
    returnCode: str
    errorText: str | None = None
    errorDevInfo: str | None = None


"""


def resolve_type(
    prop_schema: dict[str, Any], parent_name: str, prop_name: str
) -> tuple[str, tuple[str, Any] | None]:
    """Returns (type_str, inline_enum_or_None) where inline_enum is (name, values)."""
    if "$ref" in prop_schema:
        return prop_schema["$ref"].replace("#/components/schemas/", ""), None

    type_ = prop_schema.get("type")
    fmt = prop_schema.get("format")

    if type_ == "string":
        if "enum" in prop_schema:
            enum_name = parent_name + prop_name[0].upper() + prop_name[1:]
            return enum_name, (enum_name, prop_schema["enum"])
        if fmt == "date":
            return "date_aliased", None
        if fmt == "date-time":
            return "AwareDatetime", None
        return "str", None
    elif type_ == "integer":
        return "int", None
    elif type_ == "number":
        return "float", None
    elif type_ == "boolean":
        return "bool", None
    elif type_ == "array":
        items = prop_schema.get("items", {})
        singular = prop_name.removesuffix("s")
        item_type, inline = resolve_type(items, parent_name, singular)
        return f"list[{item_type}]", inline
    return "Any", None


def collect_deps(schema: dict[str, Any]) -> set[str]:
    """Collect named schema dependencies via $ref."""
    deps: set[str] = set()
    for prop_schema in schema.get("properties", {}).values():
        if "$ref" in prop_schema:
            deps.add(prop_schema["$ref"].replace("#/components/schemas/", ""))
        elif prop_schema.get("type") == "array":
            items = prop_schema.get("items", {})
            if "$ref" in items:
                deps.add(items["$ref"].replace("#/components/schemas/", ""))
    return deps


def topological_sort(schemas: dict[str, Any]) -> list[str]:
    deps = {name: collect_deps(schemas[name]) & schemas.keys() for name in schemas}
    ts = TopologicalSorter(deps)
    ts.prepare()
    result = []
    while ts.is_active():
        ready = sorted(ts.get_ready())
        result.extend(ready)
        for node in ready:
            ts.done(node)
    return result


def format_default(value: Any, enum_type: str | None = None) -> str:
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, str):
        if enum_type:
            return f"{enum_type}.{value}"
        return f"'{value}'"
    return str(value)


RESPONSE_BASE_FIELDS = {"returnCode", "errorText", "errorDevInfo"}


def generate_models(data: dict[str, Any], api_version: int) -> str:
    schemas = data["components"]["schemas"]
    ordered = topological_sort(schemas)
    output = MODELS_HEADER

    for name in ordered:
        schema = schemas[name]
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        is_request = name.endswith("Request")
        is_response = name.endswith("Response")

        inline_enums = []
        field_info = {}

        for prop_name, prop_schema in properties.items():
            if is_request and prop_name in ("language", "version"):
                continue
            if is_response and prop_name in RESPONSE_BASE_FIELDS:
                continue
            type_str, inline = resolve_type(prop_schema, name, prop_name)
            field_info[prop_name] = (
                type_str,
                prop_schema,
                inline[0] if inline else None,
            )
            if inline:
                inline_enums.append(inline)

        for enum_name, enum_values in inline_enums:
            output += f"class {enum_name}(str, Enum):\n"
            for val in enum_values:
                output += f"    {val} = '{val}'\n"
            output += "\n\n"

        base_class = "GTIResponse" if is_response else "BaseModel"
        output += f"class {name}({base_class}):\n"
        if not field_info:
            output += "    pass\n"
        else:
            for prop_name, (type_str, prop_schema, enum_type) in field_info.items():
                is_required = prop_name in required
                # Non-request models: list, AwareDatetime, and date fields without
                # an explicit default are made optional to handle partial API responses.
                if (
                    not is_request
                    and is_required
                    and (
                        type_str.startswith("list[")
                        or type_str in ("AwareDatetime", "date_aliased")
                    )
                ):
                    is_required = False
                default = prop_schema.get("default")

                if keyword.iskeyword(prop_name):
                    py_name = prop_name + "_"
                    if is_required:
                        output += f"    {py_name}: {type_str} = Field(..., alias='{prop_name}')\n"
                    elif default is not None:
                        output += f"    {py_name}: {type_str} | None = Field({format_default(default, enum_type)}, alias='{prop_name}')\n"
                    else:
                        output += f"    {py_name}: {type_str} | None = Field(None, alias='{prop_name}')\n"
                elif is_required:
                    output += f"    {prop_name}: {type_str}\n"
                elif default is not None:
                    output += f"    {prop_name}: {type_str} | None = {format_default(default, enum_type)}\n"
                else:
                    output += f"    {prop_name}: {type_str} | None = None\n"
        output += "\n\n"

    return output.rstrip("\n") + "\n"


def _patch_spec(data: dict[str, Any]) -> None:
    """Rename the vendor-duplicated operationId/schema from tariffMetaData_1."""
    schemas = data.get("components", {}).get("schemas", {})
    if "tariffMetaData_1" in schemas:
        schemas["getStationInformation"] = schemas.pop("tariffMetaData_1")
    for path_item in data.get("paths", {}).values():
        post = path_item.get("post", {})
        if post.get("operationId") == "tariffMetaData_1":
            post["operationId"] = "getStationInformation"
        for section in [
            post.get("requestBody", {}),
            *post.get("responses", {}).values(),
        ]:
            for ct in section.get("content", {}).values():
                ref = ct.get("schema", {})
                if ref.get("$ref") == "#/components/schemas/tariffMetaData_1":
                    ref["$ref"] = "#/components/schemas/getStationInformation"


if __name__ == "__main__":
    # --- Fetch spec ---

    with urllib.request.urlopen(SPEC_URL) as resp:
        data = json.loads(resp.read())
    _patch_spec(data)

    # --- Generate models.py ---

    with open("src/pygti/models.py", "w") as f:
        f.write(generate_models(data, GTI_PROTOCOL_VERSION))

    # --- Generate gti.py ---

    output = f"""# generated by scripts/codegen.py:

from .auth import Auth
<<IMPORTS>>

_GTI_PROTOCOL_VERSION = {GTI_PROTOCOL_VERSION}

class GTI:
    def __init__(self, auth: Auth, language: str = 'de'):
        self.auth = auth
        self.language = language

"""

    models: set[str] = set()

    for url, path in data.get("paths", {}).items():
        post = path.get("post")

        if not post:
            continue

        operationId = post.get("operationId").removesuffix("Public")
        requestModel = (
            post.get("requestBody")
            .get("content")
            .get("application/json")
            .get("schema")
            .get("$ref")
            .replace("#/components/schemas/", "")
        )
        responseModel = (
            post.get("responses")
            .get("200")
            .get("content")
            .get("*/*")
            .get("schema")
            .get("$ref")
            .replace("#/components/schemas/", "")
        )

        models.add(requestModel)
        models.add(responseModel)

        output += f"""
    async def {operationId}(self, payload: {requestModel}) -> {responseModel}:
        response = await self.auth.request("post", "{url}", payload, language=self.language, version=_GTI_PROTOCOL_VERSION)
        return {responseModel}.model_validate(response)

"""

    imports = ", ".join(sorted(models))
    output = output.replace("<<IMPORTS>>", f"from .models import ({imports})")

    with open("src/pygti/gti.py", "w") as f:
        f.write(output)

    subprocess.run(
        ["ruff", "format", "src/pygti/models.py", "src/pygti/gti.py"], check=True
    )
