import urllib.request
import json

url = "https://gti.geofox.de/v3/api-docs/public"


output = """# generated by scripts/codegen.py:

from .auth import Auth
<<IMPORTS>>

class GTI:
    def __init__(self, auth: Auth):
        self.auth = auth

"""

with urllib.request.urlopen(url) as response:
    data = json.loads(
        response.read().decode().replace("tariffMetaData_1", "getStationInformation")
    )


models = set()

for url, path in data.get("paths").items():
    post = path.get("post")

    if not post:
        continue

    operationId = post.get("operationId")
    requestModel = (
        post.get("requestBody")
        .get("content")
        .get("application/json")
        .get("schema")
        .get("$ref")
        .replace("#/components/schemas/", "")
    )
    responseModel = (
        post.get("responses")
        .get("200")
        .get("content")
        .get("*/*")
        .get("schema")
        .get("$ref")
        .replace("#/components/schemas/", "")
    )

    models.add(requestModel)
    models.add(responseModel)

    output += f"""
    async def {operationId}(self, payload: {requestModel}) -> {responseModel}:
        response = await self.auth.request("post", "{url}", payload)
        return {responseModel}.model_validate(response)

"""

imports = ", ".join(models)
output = output.replace("<<IMPORTS>>", f"from .models import ({imports})")

with open("src/pygti/gti.py", "w") as f:
    f.write(output)
