import urllib.request
import json
import keyword

SPEC_URL = "https://gti.geofox.de/v3/api-docs/public"
GTI_PROTOCOL_VERSION = 63

MODELS_HEADER = """# generated by scripts/codegen.py:
#   filename:  https://gti.geofox.de/v3/api-docs/public

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, Field
from enum import Enum
from datetime import date as date_aliased


"""


def resolve_type(prop_schema, parent_name, prop_name):
    """Returns (type_str, inline_enum_or_None) where inline_enum is (name, values)."""
    if "$ref" in prop_schema:
        return prop_schema["$ref"].replace("#/components/schemas/", ""), None

    type_ = prop_schema.get("type")
    fmt = prop_schema.get("format")

    if type_ == "string":
        if "enum" in prop_schema:
            enum_name = parent_name + prop_name[0].upper() + prop_name[1:]
            return enum_name, (enum_name, prop_schema["enum"])
        if fmt == "date":
            return "date_aliased", None
        if fmt == "date-time":
            return "AwareDatetime", None
        return "str", None
    elif type_ == "integer":
        return "int", None
    elif type_ == "number":
        return "float", None
    elif type_ == "boolean":
        return "bool", None
    elif type_ == "array":
        items = prop_schema.get("items", {})
        singular = prop_name.removesuffix("s")
        item_type, inline = resolve_type(items, parent_name, singular)
        return f"list[{item_type}]", inline
    return "Any", None


def collect_deps(schema):
    """Collect named schema dependencies via $ref."""
    deps = set()
    for prop_schema in schema.get("properties", {}).values():
        if "$ref" in prop_schema:
            deps.add(prop_schema["$ref"].replace("#/components/schemas/", ""))
        elif prop_schema.get("type") == "array":
            items = prop_schema.get("items", {})
            if "$ref" in items:
                deps.add(items["$ref"].replace("#/components/schemas/", ""))
    return deps


def topological_sort(schemas):
    visited = set()
    order = []

    def visit(name):
        if name in visited:
            return
        visited.add(name)
        for dep in collect_deps(schemas.get(name, {})):
            if dep in schemas:
                visit(dep)
        order.append(name)

    for name in schemas:
        visit(name)
    return order


def format_default(value):
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, str):
        return f"'{value}'"
    return str(value)


def generate_models(data, api_version):
    schemas = data["components"]["schemas"]
    ordered = topological_sort(schemas)
    output = MODELS_HEADER

    for name in ordered:
        schema = schemas[name]
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        is_request = name.endswith("Request")

        inline_enums = []
        field_info = {}

        for prop_name, prop_schema in properties.items():
            if is_request and prop_name in ("language", "version"):
                continue
            type_str, inline = resolve_type(prop_schema, name, prop_name)
            field_info[prop_name] = (type_str, prop_schema)
            if inline:
                inline_enums.append(inline)

        for enum_name, enum_values in inline_enums:
            output += f"class {enum_name}(Enum):\n"
            for val in enum_values:
                output += f"    {val} = '{val}'\n"
            output += "\n\n"

        output += f"class {name}(BaseModel):\n"
        if not field_info:
            output += "    pass\n"
        else:
            for prop_name, (type_str, prop_schema) in field_info.items():
                is_required = prop_name in required
                default = prop_schema.get("default")

                if keyword.iskeyword(prop_name):
                    py_name = prop_name + "_"
                    if is_required:
                        output += f"    {py_name}: {type_str} = Field(..., alias='{prop_name}')\n"
                    elif default is not None:
                        output += f"    {py_name}: {type_str} | None = Field({format_default(default)}, alias='{prop_name}')\n"
                    else:
                        output += f"    {py_name}: {type_str} | None = Field(None, alias='{prop_name}')\n"
                elif is_required:
                    output += f"    {prop_name}: {type_str}\n"
                elif default is not None:
                    output += f"    {prop_name}: {type_str} | None = {format_default(default)}\n"
                else:
                    output += f"    {prop_name}: {type_str} | None = None\n"
        output += "\n\n"

    return output.rstrip("\n") + "\n"


# --- Fetch spec ---

with urllib.request.urlopen(SPEC_URL) as response:
    data = json.loads(
        response.read().decode().replace("tariffMetaData_1", "getStationInformation")
    )

# --- Generate models.py ---

with open("src/pygti/models.py", "w") as f:
    f.write(generate_models(data, GTI_PROTOCOL_VERSION))

# --- Generate gti.py ---

output = f"""# generated by scripts/codegen.py:

from .auth import Auth
<<IMPORTS>>

_GTI_PROTOCOL_VERSION = {GTI_PROTOCOL_VERSION}

class GTI:
    def __init__(self, auth: Auth, language: str = 'de'):
        self.auth = auth
        self.language = language

"""

models = set()

for url, path in data.get("paths").items():
    post = path.get("post")

    if not post:
        continue

    operationId = post.get("operationId")
    requestModel = (
        post.get("requestBody")
        .get("content")
        .get("application/json")
        .get("schema")
        .get("$ref")
        .replace("#/components/schemas/", "")
    )
    responseModel = (
        post.get("responses")
        .get("200")
        .get("content")
        .get("*/*")
        .get("schema")
        .get("$ref")
        .replace("#/components/schemas/", "")
    )

    models.add(requestModel)
    models.add(responseModel)

    output += f"""
    async def {operationId}(self, payload: {requestModel}) -> {responseModel}:
        response = await self.auth.request("post", "{url}", payload, language=self.language, version=_GTI_PROTOCOL_VERSION)
        return {responseModel}.model_validate(response)

"""

imports = ", ".join(models)
output = output.replace("<<IMPORTS>>", f"from .models import ({imports})")

with open("src/pygti/gti.py", "w") as f:
    f.write(output)
